line-length = 80
indent-width = 4

target-version = "py38"

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[lint]
preview = true

select = ["ALL"]
ignore = [
    # These will eventually be enabled
    "D1",        # Docstring
    # These will not
    "COM812",    # Trailing comma missing
    "CPY",       # Missing copyright
    "DTZ",       # Timezone in datetime
    "EM101",     # Exception with string literal
    "RSE102",    # Unnecessary parentheses on raised exceptions
    "TID252",    # Prefer absolute imports
    "TRY003",    # Exception with custom text
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[lint.isort]
force-sort-within-sections = true

[lint.per-file-ignores]
"setup.py" = ["D1"]
